project:
  type: book

book:
  title: "Compuatational and Applied Mathematics"
  author: "Alexandros Giavaras"
  date: "15/04/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: linear_algebra/linear_algebra.ipynb
      chapters:
        - linear_algebra/singular_value_decomposition.ipynb
        - linear_algebra/intro_iterative_methods.ipynb
        - linear_algebra/jacobi_gauss_seidel.ipynb
        - linear_algebra/least_squares.ipynb
    - part: probability_and_statistics/probability.ipynb
      chapters:
        - probability_and_statistics/bayes_rule.ipynb     
        - probability_and_statistics/distributions/normal_distribution.ipynb
        - probability_and_statistics/simulation_methods/basic_monte_carlo_integration.ipynb 
        - probability_and_statistics/simulation_methods/importance_sampling.ipynb
    - part: probability_and_statistics/statistics/statistical_decisions/statistical_decision_theory.ipynb 
      chapters:
        - probability_and_statistics/statistics/statistical_decisions/risk_functions.ipynb 
    - part: optimization/optimization.ipynb
      chapters:
        - optimization/gradient_descent.ipynb
    - part: supervised_machine_learning.qmd
      chapters:
        - supervised_machine_learning/linear_regression.ipynb
        - supervised_machine_learning/multiple_linear_regression.ipynb
        - supervised_machine_learning/curve_fitting_probabilistic_perspective.ipynb
        - supervised_machine_learning/logistic_regression.ipynb
        - supervised_machine_learning/naive_bayes.ipynb
        - supervised_machine_learning/hidden_markov_model.ipynb
        - supervised_machine_learning/forward_algorithm.ipynb
        - supervised_machine_learning/backward_algorithm.ipynb
        - supervised_machine_learning/viterbi_algorithm.ipynb
    - part: computing_frameworks/numba_framework/numba_overview.ipynb
      chapters:
        - computing_frameworks/numba_framework/numba_automatic_parallelization.ipynb
        - computing_frameworks/numba_framework/numba_gpu_computing.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



