project:
  type: book

book:
  title: "Compuatational and Applied Mathematics"
  author: "Alexandros Giavaras"
  date: "15/04/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - part: linear_algebra.qmd
      chapters:
        - linear_algebra/intro_iterative_methods.ipynb
        - linear_algebra/jacobi_gauss_seidel.ipynb
        - linear_algebra/least_squares.ipynb
    - part: probability_theory.qmd
      chapters:
        - probability/distributions/normal_distribution.ipynb     
    - part: supervised_machine_learning.qmd
      chapters:
        - supervised_machine_learning/linear_regression.ipynb
        - supervised_machine_learning/multiple_linear_regression.ipynb
        - supervised_machine_learning/curve_fitting_probabilistic_perspective.ipynb
        - supervised_machine_learning/logistic_regression.ipynb
        - supervised_machine_learning/naive_bayes.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



